# Generated by Django 4.2.5 on 2023-10-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_sender_reply_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_allowed',
            field=models.BooleanField(default=0),
        ),
    ]
