# Generated by Django 4.2.5 on 2023-10-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_newstosend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsToSend',
        ),
    ]
